### ISSUE TITLE
Validate URL Handling

### ISSUE THREAD

**Issue by c-r-h** [ubiqx-org/Carnaval#7]
Double-check that the SMB URL parsing works as it should. 
 1. Should an empty path be represented as "" or "/"?
 2. Are escaped characters being properly protected? 

Add Doctest checks.

**Comment by jarrpa** [comment]
1. I say empty string ( "" ).
2. Doesn't seem like this is a necessary step. I would update the comments for SMB_URL._cleanStrField() to not talk about escaping/unescaping, and comment wherever it is that you talk about your input that input strings should be properly escaped before being passed to SMB_URL.

**Comment by c-r-h** [comment]
1. It's a question for the RFCs that describe the general URL/URI format.  There may be a requirement one way or the other.  I need to check.
2. The comments in _cleanStrField() have been updated.  I still want to make sure that the code is handling URL-escapes correctly, but that will take some testing (and possibly field validation) that can't be done until/unless we have working SMB2 code (or, perhaps, a browse service probe tool that accepts the SMB URL format).

**Comment by jarrpa** [comment]
1. https://tools.ietf.org/html/rfc3986#section-3.3 No requirements one way or another. I'd say go with the preference of not altering user input where not necessary and return all components of the URI as the user provided them unless an error is found.
2. Cool.

**Comment by c-r-h** [comment]
Resolving the ticket. 

I am satisfied with the answer that the empty path may be represented either as "" (the empty string) or "/".
